In [6]:
import math

board = [' ' for _ in range(9)]


def print_board():
    for i in range(3):
        print(board[i*3] + "|" + board[i*3+1] + "|" + board[i*3+2])
        if i < 2:
            print("-+-+-")


def check_winner(brd, player):
    win_states = [
        [0,1,2], [3,4,5], [6,7,8],
        [0,3,6], [1,4,7], [2,5,8],
        [0,4,8], [2,4,6]
    ]
    for state in win_states:
        if all(brd[i] == player for i in state):
            return True
    return False


def is_full(brd):
    return ' ' not in brd


def minimax(brd, depth, is_maximizing):
    if check_winner(brd, 'O'):
        return 1
    if check_winner(brd, 'X'):
        return -1
    if is_full(brd):
        return 0

    if is_maximizing:
        best_score = -math.inf
        for i in range(9):
            if brd[i] == ' ':
                brd[i] = 'O'
                score = minimax(brd, depth + 1, False)
                brd[i] = ' '
                best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for i in range(9):
            if brd[i] == ' ':
                brd[i] = 'X'
                score = minimax(brd, depth + 1, True)
                brd[i] = ' '
                best_score = min(score, best_score)
        return best_score


def computer_move():
    best_score = -math.inf
    move = None
    for i in range(9):
        if board[i] == ' ':
            board[i] = 'O'
            score = minimax(board, 0, False)
            board[i] = ' '
            if score > best_score:
                best_score = score
                move = i
    board[move] = 'O'


def main():
    print("Welcome to Tic Tac Toe!")
    print("You are X, computer is O.")
    print_board()

    while True:

        move = int(input("Enter your move (0-8): "))
        if board[move] != ' ':
            print("Invalid move. Try again.")
            continue
        board[move] = 'X'
        print_board()

        if check_winner(board, 'X'):
            print("You win!")
            break
        if is_full(board):
            print("It's a draw!")
            break

        computer_move()
        print("Computer played:")
        print_board()

        if check_winner(board, 'O'):
            print("Computer wins!")
            break
        if is_full(board):
            print("It's a draw!")
            break

main()


Welcome to Tic Tac Toe!
You are X, computer is O.
 | | 
-+-+-
 | | 
-+-+-
 | | 
Enter your move (0-8): 3
 | | 
-+-+-
X| | 
-+-+-
 | | 
Computer played:
O| | 
-+-+-
X| | 
-+-+-
 | | 
Enter your move (0-8): 2
O| |X
-+-+-
X| | 
-+-+-
 | | 
Computer played:
O| |X
-+-+-
X|O| 
-+-+-
 | | 
Enter your move (0-8): 4
Invalid move. Try again.
Enter your move (0-8): 5
O| |X
-+-+-
X|O|X
-+-+-
 | | 
Computer played:
O| |X
-+-+-
X|O|X
-+-+-
 | |O
Computer wins!


In [ ]:
!pip install pyspellchecker

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 34.1 MB/s eta 0:00:00


In [ ]:
import re
import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from spellchecker import SpellChecker


In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
nltk_data_path = nltk.data.path
nltk_data_path.append('/content/nltk_data')

In [ ]:
# reading text file
def read_file(path):
    with open(path,'r') as f:
      text = f.read()
    return text


In [ ]:
text = read_file('/content/text.txt')
text

"Urban architecture has evolved dramatically over the past century, transforming skylines across the globe with innovative designs and sustainable approaches. Modern cities now feature a striking blend of glass-clad skyscrapers, revitalized industrial zones, and green spaces that serve as communal gathering spots. Architects increasingly focus on creating structures that harmonize with their surroundings while incorporating environmentally responsible features. The relationship between buildings and public spaces has become a central consideration in urban planning, with many cities investing in pedestrian-friendly areas that encourage community interaction. Public transportation hubs are now designed as architectural focal points rather than merely functional spaces, serving as gateways that define a city's character. Historic preservation has gained importance, with developers finding creative ways to repurpose older buildings while maintaining their cultural significance. Mixed-use 

In [ ]:
def lower(text):
  text = text.lower()
  return text

In [ ]:
low = lower(text)
low


"urban architecture has evolved dramatically over the past century, transforming skylines across the globe with innovative designs and sustainable approaches. modern cities now feature a striking blend of glass-clad skyscrapers, revitalized industrial zones, and green spaces that serve as communal gathering spots. architects increasingly focus on creating structures that harmonize with their surroundings while incorporating environmentally responsible features. the relationship between buildings and public spaces has become a central consideration in urban planning, with many cities investing in pedestrian-friendly areas that encourage community interaction. public transportation hubs are now designed as architectural focal points rather than merely functional spaces, serving as gateways that define a city's character. historic preservation has gained importance, with developers finding creative ways to repurpose older buildings while maintaining their cultural significance. mixed-use 

In [ ]:
def cleaning(text):
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [ ]:
clean = cleaning(low)
clean

'urban architecture has evolved dramatically over the past century transforming skylines across the globe with innovative designs and sustainable approaches modern cities now feature a striking blend of glassclad skyscrapers revitalized industrial zones and green spaces that serve as communal gathering spots architects increasingly focus on creating structures that harmonize with their surroundings while incorporating environmentally responsible features the relationship between buildings and public spaces has become a central consideration in urban planning with many cities investing in pedestrianfriendly areas that encourage community interaction public transportation hubs are now designed as architectural focal points rather than merely functional spaces serving as gateways that define a citys character historic preservation has gained importance with developers finding creative ways to repurpose older buildings while maintaining their cultural significance mixeduse developments hav

In [ ]:
def tokenize(text):
  sent_tokens = sent_tokenize(text)
  word_tokens = word_tokenize(text)
  return sent_tokens, word_tokens

In [ ]:
sent,word = tokenize(clean)
word

['urban',
 'architecture',
 'has',
 'evolved',
 'dramatically',
 'over',
 'the',
 'past',
 'century',
 'transforming',
 'skylines',
 'across',
 'the',
 'globe',
 'with',
 'innovative',
 'designs',
 'and',
 'sustainable',
 'approaches',
 'modern',
 'cities',
 'now',
 'feature',
 'a',
 'striking',
 'blend',
 'of',
 'glassclad',
 'skyscrapers',
 'revitalized',
 'industrial',
 'zones',
 'and',
 'green',
 'spaces',
 'that',
 'serve',
 'as',
 'communal',
 'gathering',
 'spots',
 'architects',
 'increasingly',
 'focus',
 'on',
 'creating',
 'structures',
 'that',
 'harmonize',
 'with',
 'their',
 'surroundings',
 'while',
 'incorporating',
 'environmentally',
 'responsible',
 'features',
 'the',
 'relationship',
 'between',
 'buildings',
 'and',
 'public',
 'spaces',
 'has',
 'become',
 'a',
 'central',
 'consideration',
 'in',
 'urban',
 'planning',
 'with',
 'many',
 'cities',
 'investing',
 'in',
 'pedestrianfriendly',
 'areas',
 'that',
 'encourage',
 'community',
 'interaction',
 'public

In [ ]:
def remove_stopwords(text): # Changed function name to avoid conflict
  stop_words = set(nltk.corpus.stopwords.words('english'))
  filtered_words = [word for word in text if word not in stop_words]
  return filtered_words

stop = remove_stopwords(word) # Calling the updated function
stop

['urban',
 'architecture',
 'evolved',
 'dramatically',
 'past',
 'century',
 'transforming',
 'skylines',
 'across',
 'globe',
 'innovative',
 'designs',
 'sustainable',
 'approaches',
 'modern',
 'cities',
 'feature',
 'striking',
 'blend',
 'glassclad',
 'skyscrapers',
 'revitalized',
 'industrial',
 'zones',
 'green',
 'spaces',
 'serve',
 'communal',
 'gathering',
 'spots',
 'architects',
 'increasingly',
 'focus',
 'creating',
 'structures',
 'harmonize',
 'surroundings',
 'incorporating',
 'environmentally',
 'responsible',
 'features',
 'relationship',
 'buildings',
 'public',
 'spaces',
 'become',
 'central',
 'consideration',
 'urban',
 'planning',
 'many',
 'cities',
 'investing',
 'pedestrianfriendly',
 'areas',
 'encourage',
 'community',
 'interaction',
 'public',
 'transportation',
 'hubs',
 'designed',
 'architectural',
 'focal',
 'points',
 'rather',
 'merely',
 'functional',
 'spaces',
 'serving',
 'gateways',
 'define',
 'citys',
 'character',
 'historic',
 'preserva

In [ ]:
def correct(text):
  spell = SpellChecker()
  corrected_text = []
  for word in text:
    if word in spell:
      corrected_text.append(word)
    else:
      correction = spell.correction(word)
      corrected_text.append(correction if correction is not None else word)
  return corrected_text


In [ ]:
corrected = correct(stop)
corrected

['urban',
 'architecture',
 'evolved',
 'dramatically',
 'past',
 'century',
 'transforming',
 'skylines',
 'across',
 'globe',
 'innovative',
 'designs',
 'sustainable',
 'approaches',
 'modern',
 'cities',
 'feature',
 'striking',
 'blend',
 'glassclad',
 'skyscrapers',
 'revitalized',
 'industrial',
 'zones',
 'green',
 'spaces',
 'serve',
 'communal',
 'gathering',
 'spots',
 'architects',
 'increasingly',
 'focus',
 'creating',
 'structures',
 'harmonize',
 'surroundings',
 'incorporating',
 'environmentally',
 'responsible',
 'features',
 'relationship',
 'buildings',
 'public',
 'spaces',
 'become',
 'central',
 'consideration',
 'urban',
 'planning',
 'many',
 'cities',
 'investing',
 'pedestrianfriendly',
 'areas',
 'encourage',
 'community',
 'interaction',
 'public',
 'transportation',
 'hubs',
 'designed',
 'architectural',
 'focal',
 'points',
 'rather',
 'merely',
 'functional',
 'spaces',
 'serving',
 'gateways',
 'define',
 'city',
 'character',
 'historic',
 'preservat

In [ ]:
def stemming(text):
  stem = PorterStemmer()
  stemmed_words = [stem.stem(word) for word in text]
  return stemmed_words

stemmed = stemming(corrected)
stemmed

['urban',
 'architectur',
 'evolv',
 'dramat',
 'past',
 'centuri',
 'transform',
 'skylin',
 'across',
 'globe',
 'innov',
 'design',
 'sustain',
 'approach',
 'modern',
 'citi',
 'featur',
 'strike',
 'blend',
 'glassclad',
 'skyscrap',
 'revit',
 'industri',
 'zone',
 'green',
 'space',
 'serv',
 'commun',
 'gather',
 'spot',
 'architect',
 'increasingli',
 'focu',
 'creat',
 'structur',
 'harmon',
 'surround',
 'incorpor',
 'environment',
 'respons',
 'featur',
 'relationship',
 'build',
 'public',
 'space',
 'becom',
 'central',
 'consider',
 'urban',
 'plan',
 'mani',
 'citi',
 'invest',
 'pedestrianfriendli',
 'area',
 'encourag',
 'commun',
 'interact',
 'public',
 'transport',
 'hub',
 'design',
 'architectur',
 'focal',
 'point',
 'rather',
 'mere',
 'function',
 'space',
 'serv',
 'gateway',
 'defin',
 'citi',
 'charact',
 'histor',
 'preserv',
 'gain',
 'import',
 'develop',
 'find',
 'creativ',
 'way',
 'purpos',
 'older',
 'build',
 'maintain',
 'cultur',
 'signific',
 'm

In [ ]:
def lemmatize(text):
  lemmatizer = WordNetLemmatizer()
  lemmatized_words = [lemmatizer.lemmatize(word) for word in text]
  return lemmatized_words

In [ ]:
lemmatized = lemmatize(stemmed)
lemmatized

['urban',
 'architectur',
 'evolv',
 'dramat',
 'past',
 'centuri',
 'transform',
 'skylin',
 'across',
 'globe',
 'innov',
 'design',
 'sustain',
 'approach',
 'modern',
 'citi',
 'featur',
 'strike',
 'blend',
 'glassclad',
 'skyscrap',
 'revit',
 'industri',
 'zone',
 'green',
 'space',
 'serv',
 'commun',
 'gather',
 'spot',
 'architect',
 'increasingli',
 'focu',
 'creat',
 'structur',
 'harmon',
 'surround',
 'incorpor',
 'environment',
 'respons',
 'featur',
 'relationship',
 'build',
 'public',
 'space',
 'becom',
 'central',
 'consider',
 'urban',
 'plan',
 'mani',
 'citi',
 'invest',
 'pedestrianfriendli',
 'area',
 'encourag',
 'commun',
 'interact',
 'public',
 'transport',
 'hub',
 'design',
 'architectur',
 'focal',
 'point',
 'rather',
 'mere',
 'function',
 'space',
 'serv',
 'gateway',
 'defin',
 'citi',
 'charact',
 'histor',
 'preserv',
 'gain',
 'import',
 'develop',
 'find',
 'creativ',
 'way',
 'purpos',
 'older',
 'build',
 'maintain',
 'cultur',
 'signific',
 'm

In [ ]:
from nltk.util import ngrams
def create_trigrams(words):
    return list(ngrams(words, 3))

In [ ]:
create_trigrams(lemmatized)

[('urban', 'architectur', 'evolv'),
 ('architectur', 'evolv', 'dramat'),
 ('evolv', 'dramat', 'past'),
 ('dramat', 'past', 'centuri'),
 ('past', 'centuri', 'transform'),
 ('centuri', 'transform', 'skylin'),
 ('transform', 'skylin', 'across'),
 ('skylin', 'across', 'globe'),
 ('across', 'globe', 'innov'),
 ('globe', 'innov', 'design'),
 ('innov', 'design', 'sustain'),
 ('design', 'sustain', 'approach'),
 ('sustain', 'approach', 'modern'),
 ('approach', 'modern', 'citi'),
 ('modern', 'citi', 'featur'),
 ('citi', 'featur', 'strike'),
 ('featur', 'strike', 'blend'),
 ('strike', 'blend', 'glassclad'),
 ('blend', 'glassclad', 'skyscrap'),
 ('glassclad', 'skyscrap', 'revit'),
 ('skyscrap', 'revit', 'industri'),
 ('revit', 'industri', 'zone'),
 ('industri', 'zone', 'green'),
 ('zone', 'green', 'space'),
 ('green', 'space', 'serv'),
 ('space', 'serv', 'commun'),
 ('serv', 'commun', 'gather'),
 ('commun', 'gather', 'spot'),
 ('gather', 'spot', 'architect'),
 ('spot', 'architect', 'increasingli')

# Fuzzy Sets


In [ ]:
# Define fuzzy set operations
def fuzzy_union(set1, set2):
    return {x: max(set1.get(x, 0), set2.get(x, 0)) for x in set(set1) | set(set2)}

def fuzzy_intersection(set1, set2):
    return {x: min(set1.get(x, 0), set2.get(x, 0)) for x in set(set1) | set(set2)}

def fuzzy_complement(fuzzy_set):
    return {x: round(1 - val, 2) for x, val in fuzzy_set.items()}

# Example fuzzy sets
A = {'a': 0.2, 'b': 0.5, 'c': 0.7}
B = {'a': 0.6, 'b': 0.3, 'c': 0.8}
C = {'a': 0.1, 'b': 0.9, 'c': 0.4}

print("Fuzzy Set A:", A)
print("Fuzzy Set B:", B)
print("Fuzzy Set C:", C)

# Perform operations between A and B
union_AB = fuzzy_union(A, B)
intersection_AB = fuzzy_intersection(A, B)
complement_A = fuzzy_complement(A)
complement_B = fuzzy_complement(B)

print("\nUnion of A and B:", union_AB)
print("Intersection of A and B:", intersection_AB)
print("Complement of A:", complement_A)
print("Complement of B:", complement_B)

# Demonstrate De Morgan’s Law 1:
# Complement of (A union B) == Intersection of (Complement of A) and (Complement of B)
complement_union_AB = fuzzy_complement(union_AB)
intersection_complements = fuzzy_intersection(complement_A, complement_B)

print("\nDe Morgan’s Law 1:")
print("Complement of Union (A ∪ B):", complement_union_AB)
print("Intersection of Complements (A' ∩ B'):", intersection_complements)

# Verify De Morgan's Law 1
print("Law 1 Verified:", complement_union_AB == intersection_complements)

# Demonstrate De Morgan’s Law 2:
# Complement of (A intersection B) == Union of (Complement of A) and (Complement of B)
complement_intersection_AB = fuzzy_complement(intersection_AB)
union_complements = fuzzy_union(complement_A, complement_B)

print("\nDe Morgan’s Law 2:")
print("Complement of Intersection (A ∩ B):", complement_intersection_AB)
print("Union of Complements (A' ∪ B'):", union_complements)

# Verify De Morgan's Law 2
print("Law 2 Verified:", complement_intersection_AB == union_complements)

# Bonus: operations with 3 fuzzy sets (A, B, C)
print("\n--- Operations with 3 fuzzy sets A, B, C ---")
union_ABC = fuzzy_union(fuzzy_union(A, B), C)
intersection_ABC = fuzzy_intersection(fuzzy_intersection(A, B), C)

print("Union of A, B, and C:", union_ABC)
print("Intersection of A, B, and C:", intersection_ABC)


Fuzzy Set A: {'a': 0.2, 'b': 0.5, 'c': 0.7}
Fuzzy Set B: {'a': 0.6, 'b': 0.3, 'c': 0.8}
Fuzzy Set C: {'a': 0.1, 'b': 0.9, 'c': 0.4}

Union of A and B: {'c': 0.8, 'a': 0.6, 'b': 0.5}
Intersection of A and B: {'c': 0.7, 'a': 0.2, 'b': 0.3}
Complement of A: {'a': 0.8, 'b': 0.5, 'c': 0.3}
Complement of B: {'a': 0.4, 'b': 0.7, 'c': 0.2}

De Morgan’s Law 1:
Complement of Union (A ∪ B): {'c': 0.2, 'a': 0.4, 'b': 0.5}
Intersection of Complements (A' ∩ B'): {'c': 0.2, 'a': 0.4, 'b': 0.5}
Law 1 Verified: True

De Morgan’s Law 2:
Complement of Intersection (A ∩ B): {'c': 0.3, 'a': 0.8, 'b': 0.7}
Union of Complements (A' ∪ B'): {'c': 0.3, 'a': 0.8, 'b': 0.7}
Law 2 Verified: True

--- Operations with 3 fuzzy sets A, B, C ---
Union of A, B, and C: {'c': 0.8, 'a': 0.6, 'b': 0.9}
Intersection of A, B, and C: {'c': 0.4, 'a': 0.1, 'b': 0.3}


In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))
N = 5
input_size = N
hidden1_size = 4
hidden2_size = 3
output_size = 1

W1 = np.random.randn(hidden1_size, input_size)
b1 = np.random.randn(hidden1_size, 1)

W2 = np.random.randn(hidden2_size, hidden1_size)
b2 = np.random.randn(hidden2_size, 1)

W3 = np.random.randn(output_size, hidden2_size)
b3 = np.random.randn(output_size, 1)

print("W1 =", W1)
print("b1 =", b1)
print("W2 =", W2)
print("b2 =", b2)
print("W3 =", W3)
print("b3 =", b3)

x = np.random.randint(0, 2, (input_size, 1))
print("Input x =", x)

z1 = np.dot(W1, x) + b1
a1 = sigmoid(z1)

z2 = np.dot(W2, a1) + b2
a2 = sigmoid(z2)

z3 = np.dot(W3, a2) + b3
a3 = sigmoid(z3)

output = a3
print("Output =", output)

W1 = [[ 2.15650449 -0.26378011 -1.71371181  0.10701973  1.33952554]
 [ 0.48410078  0.69156344  0.37564271  0.36998219  0.50290779]
 [ 2.20641346  0.54911544 -1.38172249 -1.48033754 -0.78797881]
 [ 1.30733891 -0.6961865  -0.99339011  0.58398468 -0.15613051]]
b1 = [[-0.84182444]
 [-0.10841099]
 [ 0.56161687]
 [-0.94209443]]
W2 = [[ 0.09222532 -0.74508184  0.85372792 -1.51852047]
 [ 0.74071377 -1.30484801 -1.03245436 -0.27064245]
 [ 0.56660433  0.47827904  1.26813428 -0.48380385]]
b2 = [[-0.59683092]
 [ 0.95370258]
 [-0.00239604]]
W3 = [[ 2.1665624  -1.61231282 -0.26879784]]
b3 = [[0.66238523]]
Input x = [[0]
 [0]
 [1]
 [1]
 [0]]
Output = [[0.53823316]]


In [ ]:
import numpy as np

N = 4
hidden1 = 5
hidden2 = 3
output = 1
X = np.random.randint(0, 2, (10, N))
steps = 0
while True:
    steps += 1

    W1 = np.random.randn(N, hidden1)
    b1 = np.random.randn(hidden1)

    W2 = np.random.randn(hidden1, hidden2)
    b2 = np.random.randn(hidden2)

    W3 = np.random.randn(hidden2, output)
    b3 = np.random.randn(output)


    h1 = np.dot(X, W1) + b1
    h2 = np.dot(h1, W2) + b2
    y_pred = np.dot(h2, W3) + b3

    if steps >= 5:
        break

print("Final W1:\n", W1)
print("Final b1:\n", b1)
print("Final W2:\n", W2)
print("Final b2:\n", b2)
print("Final W3:\n", W3)
print("Final b3:\n", b3)
print("Final pref\d:\n",y_pred)
print("Steps:", steps)


Final W1:
 [[ 1.30638384 -0.70020386  0.87124055 -0.96447886 -2.41415849]
 [ 1.06412358 -1.80876938 -0.13338214  0.22233657 -1.76302275]
 [-0.51445162  1.32878113  0.34309209  0.43534946 -0.22601823]
 [ 0.73732676  1.52181575 -0.13284911 -0.60857945  0.93052321]]
Final b1:
 [ 0.82910764 -0.99822583 -0.89821128  1.00294512 -0.08379344]
Final W2:
 [[-0.84190754  1.08605826  1.79287351]
 [ 1.46985036 -2.21155893  0.79043892]
 [-0.2935456   0.3744469   2.22510657]
 [-0.05996982  0.81370636 -1.33412815]
 [-0.50391127 -0.56914305  0.60120641]]
Final b2:
 [-0.41374994  2.25493547  0.03905437]
Final W3:
 [[ 0.52486794]
 [-0.73082549]
 [-0.19394059]]
Final b3:
 [1.3601325]
Final pref\d:
 [[-5.16364005]
 [ 2.26875957]
 [-7.76681518]
 [-1.05222857]
 [-9.41037944]
 [-9.41037944]
 [-3.65540369]
 [ 2.26875957]
 [-4.44582704]
 [ 2.26875957]]
Steps: 5


In [ ]:
import heapq

graph = {}

n = int(input("Enter number of edges: "))
for _ in range(n):
    u, v, w = input().split()
    w = int(w)
    if u not in graph:
        graph[u] = []
    graph[u].append((v, w))

heuristics = {}
m = int(input("Enter number of nodes for heuristics: "))
for _ in range(m):
    node, h = input().split()
    heuristics[node] = int(h)

def best_first_search(graph, heuristics, start, goal):
    visited = set()
    priority_queue = []
    heapq.heappush(priority_queue, (heuristics[start], start))

    while priority_queue:
        cost, current_node = heapq.heappop(priority_queue)
        print(f"Visiting: {current_node}")

        if current_node == goal:
            print("Goal reached!")
            return

        visited.add(current_node)

        for neighbor, weight in graph.get(current_node, []):
            if neighbor not in visited:
                heapq.heappush(priority_queue, (heuristics[neighbor], neighbor))

start_node = input("Enter start node: ").strip()
goal_node = input("Enter goal node: ").strip()

best_first_search(graph, heuristics, start_node, goal_node)

In [ ]:
import numpy as np


def sigmoid(x):
  return 1/(1+np.exp(-x))
def d_sigmoid(x):
  return sigmoid(x)*(1-sigmoid(x))
N = 4
hidden1 = 5
hidden2 = 3
output = 1
lr = 0.1

X = np.random.randint(0, 2, (10, N))
y = np.random.randint(0, 2, (10, output))

W1 = np.random.randn(N,hidden1)
b1 = np.zeros((1,hidden1))
W2 = np.random.randn(hidden1,hidden2)
b2 = np.zeros((1,hidden2))
W3 = np.random.randn(hidden2,output)
b3 = np.zeros((1,output))

steps = 0
for epoch in range(1000):
  steps+=1

  z1 = np.dot(X,W1) + b1
  a1 = sigmoid(z1)
  z2 = np.dot(a1,W2)+b2
  a2 = sigmoid(z2)
  z3 = np.dot(a2,W3)+b3
  y_pred = sigmoid(z3)

  loss = np.mean((y-y_pred)**2)
  d_loss = 2*(y-y_pred)*d_sigmoid(z3)

  dW3 = np.dot(a2.T, d_loss)
  db3 = np.sum(d_loss, axis=0, keepdims=True)

  d_hidden2 = np.dot(d_loss, W3.T) * d_sigmoid(z2)
  dW2 = np.dot(a1.T, d_hidden2)
  db2 = np.sum(d_hidden2, axis=0, keepdims=True)

  d_hidden1 = np.dot(d_hidden2, W2.T) * d_sigmoid(z1)
  dW1 = np.dot(X.T, d_hidden1)
  db1 = np.sum(d_hidden1, axis=0, keepdims=True)

  W3 -= lr * dW3
  b3 -= lr * db3
  W2 -= lr * dW2
  b2 -= lr * db2
  W1 -= lr * dW1
  b1 -= lr * db1
  if loss < 0.3:
        break


print("Final W1:\n", W1)
print("Final b1:\n", b1)
print("Final W2:\n", W2)
print("Final b2:\n", b2)
print("Final W3:\n", W3)
print("Final b3:\n", b3)
print("Steps:", steps)
print("final_loss:", loss)

Final W1:
 [[-0.82077478 -0.49640505  0.79468254  0.78940127 -0.70541119]
 [ 0.78365168  1.43419578 -0.64643637  0.5984429  -2.04626396]
 [-0.26063375 -0.0156302  -0.64256815 -0.96741476  0.35597455]
 [ 0.89710852 -1.21807581  0.7846379  -1.85878644 -1.42562088]]
Final b1:
 [[0.00387737 0.00388639 0.00112108 0.0001398  0.00570063]]
Final W2:
 [[-0.22179778 -0.28557805 -2.2333712 ]
 [-1.48771211 -1.56384859 -1.00021901]
 [-0.29951594  1.05190123 -1.23281366]
 [ 0.08482066 -0.22826762 -0.15047316]
 [-1.04309493 -0.74237166 -0.9078932 ]]
Final b2:
 [[-0.00648851 -0.00311404 -0.00508301]]
Final W3:
 [[1.48630664]
 [0.51115506]
 [1.84334732]]
Final b3:
 [[-0.01723536]]
Steps: 1
final_loss: 0.1984202487513401


In [ ]:
d_loss = 2*(y-y_pred)*d_sigmoid(z3)
dW3 = np.dot(a2.T,d_loss)
db3 = np.sum(d_loss,axis = 0, keepdims = True)

d_hidden2 = np.dot(d_loss, W3.T)*d_sigmoid(z2)
dW2 = np.dot(a1.T,d_hidden2)
db2 = np.sum(d_hidden2,axis =0, keepdims=True)

d_hidden3 = np.dot(d_hidden2,W2.T)*d_sigmoid(z1)
dw1 = np.dot(X.T,d_hidden3)
db1 = np.sum(d_hidden3,axis=0,keepdims=True)